language: objective-c

osx_image: xcode7

#xcode_scheme: WatsonCore

branches:
  only:
     - master

script:
- xcodebuild clean build test -scheme LanguageTranslation -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0'
