language: objective-c

osx_image: xcode7.1

#xcode_scheme: WatsonCore

branches:
  only:
     - master

after_success:
- bash <(curl -s https://codecov.io/bash)

script:
- xcodebuild clean build  -scheme WatsonSDK -enableCodeCoverage YES -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0' GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES 
