language: objective-c

osx_image: xcode7

#xcode_scheme: WatsonCore

branches:
  only:
     - develop

script:
- xcodebuild clean build -scheme WatsonSDK -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0'
