# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
# This workflow will do a clean install of swift dependencies, build the source code and run tests across different versions of swift
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build and Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_test:
    name: Build and Test on Swift ${{ matrix.swift-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        swift-version: ['5.3']
        os: [macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Swift
      uses: fwal/setup-swift@@v1
      with:
        swift-version: ${{ matrix.swift-version }}

    - name: Get swift version
      run: |
         swift --version
         xcodebuild -version

    - name: Validate Pods
      run: Scripts/pod-lint.sh
